volumes:
  pasquali_db-vol:
services:
  pasquali_db:
    container_name: pasquali_db
    image: mysql:5.7.22
    volumes:
      - ./docker/mysql_db:/var/lib/mysql
    ports:
      - '3307:3306'
    command: --max_allowed_packet=444194304
    environment:
      - MAX_EXECUTION_TIME=6000
      - MAX_INPUT_TIME=6000
      - MEMORY_LIMIT=2048M
      - POST_MAX_SIZE=2048M
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=pasquali
      - MYSQL_USER=diego
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_HOST=127.0.0.1
    networks:
      - laravel
  pasquali_pma:
    container_name: pasquali_pma
    image: phpmyadmin/phpmyadmin:latest
    links:
      - pasquali_db
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=1000000000
    networks:
      - laravel
  pasquali_redis:
    container_name: pasquali_redis
    image: redis
    command: redis-server --requirepass Redis!
    ports:
      - "6378:6379"
    networks:
      - laravel
  pasquali_site:
    container_name: pasquali_site
    build:
      args:
        user: diego
        uid: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - pasquali_redis
    networks:
      - laravel
  pasquali_nginx:
    container_name: 'pasquali_nginx'
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
